[package]
name = "migration"
version = "0.2.3"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
entity = { path = "../entity" }
sea-orm-migration = { version = "^0.8.0" }
tokio = { version = "1.17.0", features = ["full"] }
