[package]
name = "migration"
version = "0.2.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
entity = { path = "../entity" }
sea-schema = { version = "^0.7.0", default-features = false, features = [ "migration", "debug-print" ] }
