//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "purchase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub buyer: u32,
    pub product: u32,
    pub quantity: u32,
    pub unit_price: u32,
    pub date: DateTimeUtc,
    pub paid_date: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::Buyer",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    User,
    #[sea_orm(
        belongs_to = "super::product::Entity",
        from = "Column::Product",
        to = "super::product::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Product,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Product.def()
    }
}

impl ActiveModelBehavior for ActiveModel {
    // Will be triggered before insert / update
    fn before_save(self, insert: bool) -> Result<Self, DbErr> {
        if self.quantity.is_set() && self.quantity.as_ref() <= &0 {
            Err(DbErr::Custom(format!(
                "[before_save] Quantity cannot be zero, insert: {}",
                insert
            )))
        } else {
            Ok(self)
        }
    }
}
