[package]
name = "entity"
version = "0.2.3"
edition = "2021"
publish = false

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
sea-orm = { version = "^0.8.0", features = [ "sqlx-mysql", "runtime-tokio-native-tls", "macros" ] }
